apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./templates/clusterrole.yaml
  - ./templates/clusterrolebinding.yaml
  - ./templates/cronjob-ca-certSelfSigner.yaml
  - ./templates/cronjob-client-node-certSelfSigner.yaml
  - ./templates/job-certSelfSigner.yaml
  - ./templates/job-cleaner.yaml
  - ./templates/job.init.yaml
  - ./templates/poddisruptionbudget.yaml
  - ./templates/role-certRotateSelfSigner.yaml
  - ./templates/role-certSelfSigner.yaml
  - ./templates/role.yaml
  - ./templates/rolebinding-certRotateSelfSigner.yaml
  - ./templates/rolebinding-certSelfSigner.yaml
  - ./templates/rolebinding.yaml
  - ./templates/service.discovery.yaml
  - ./templates/service.public.yaml
  - ./templates/service.visus.yaml
  - ./templates/serviceaccount-certRotateSelfSigner.yaml
  - ./templates/serviceaccount-certSelfSigner.yaml
  - ./templates/serviceaccount.yaml
  - ./templates/statefulset.yaml

patches:
  - target:
      group: batch
      version: v1beta1
      kind: CronJob
      name: cockroachdb-rotate-self-signer
    path: chart-patch.yaml
  - target:
      group: batch
      version: v1beta1
      kind: CronJob
      name: cockroachdb-rotate-self-signer-client
    path: chart-patch.yaml
