---
# Source: zitadel/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: zitadel
  labels:
    helm.sh/chart: zitadel-8.13.4
    app.kubernetes.io/name: zitadel
    app.kubernetes.io/instance: zitadel
    app.kubernetes.io/version: "v2.67.2"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http2-server
      appProtocol: kubernetes.io/h2c
  selector:
    app.kubernetes.io/name: zitadel
    app.kubernetes.io/instance: zitadel
