---
# Source: zitadel/templates/setupjob.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: "zitadel-setup"
  labels:
    helm.sh/chart: zitadel-8.13.4
    app.kubernetes.io/name: zitadel
    app.kubernetes.io/instance: zitadel
    app.kubernetes.io/version: "v2.67.2"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: setup
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "2"
spec:
  backoffLimit: 5
  activeDeadlineSeconds: 300
  template:
    metadata:
      labels:
        helm.sh/chart: zitadel-8.13.4
        app.kubernetes.io/name: zitadel
        app.kubernetes.io/instance: zitadel
        app.kubernetes.io/version: "v2.67.2"
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: setup
    spec:
      serviceAccountName: zitadel
      securityContext:
        fsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      enableServiceLinks: false
      restartPolicy: OnFailure
      containers:
        - name: "zitadel-setup"
          securityContext:
              privileged: false
              readOnlyRootFilesystem: true
              runAsNonRoot: true
              runAsUser: 1000
          image: "ghcr.io/zitadel/zitadel:v2.67.2"
          imagePullPolicy: IfNotPresent
          args:
            - setup
            - --masterkeyFromEnv
            - --config
            - /config/zitadel-config-yaml
            - --steps
            - /config/zitadel-config-yaml
            - --init-projections=true
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: ZITADEL_MASTERKEY
              valueFrom:
                secretKeyRef:
                  name: zitadel-masterkey
                  key: masterkey
            - name: ZITADEL_FIRSTINSTANCE_MACHINEKEYPATH
              value: "/machinekey/sa.json"
          volumeMounts:
          - name: zitadel-config-yaml
            mountPath: /config
            readOnly: true
          resources:
            {}
      volumes:
      - name: zitadel-config-yaml
        configMap:
          name: zitadel-config-yaml
          defaultMode: 0440
