---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kratos-config
data:
  "kratos.yaml": |
    # Database connection string - using in-memory SQLite for development
    dsn: sqlite://file:memdb1?mode=memory&cache=shared
    
    courier:
      smtp: {}
    
    serve:
      admin:
        port: 4434
      public:
        port: 4433
    
    # Self-service configuration
    selfservice:
      default_browser_return_url: http://localhost:4455/
      allowed_return_urls:
        - http://localhost:4455/
        - http://127.0.0.1:4455/
      
      methods:
        password:
          enabled: true
        totp:
          config:
            issuer: Kratos
          enabled: true
        lookup_secret:
          enabled: true
        webauthn:
          config:
            passwordless: false
            rp:
              display_name: Kratos
              id: localhost
              origins:
                - http://localhost:4455
          enabled: true
        link:
          enabled: true
        code:
          enabled: true
      
      flows:
        error:
          ui_url: http://localhost:4455/error
        
        settings:
          ui_url: http://localhost:4455/settings
          privileged_session_max_age: 15m
          required_aal: highest_available
        
        recovery:
          enabled: true
          ui_url: http://localhost:4455/recovery
          use: code
        
        verification:
          enabled: true
          ui_url: http://localhost:4455/verification
          use: code
          after:
            default_browser_return_url: http://localhost:4455/
        
        logout:
          after:
            default_browser_return_url: http://localhost:4455/
        
        login:
          ui_url: http://localhost:4455/login
          lifespan: 10m
          after:
            default_browser_return_url: http://localhost:4455/
        
        registration:
          lifespan: 10m
          ui_url: http://localhost:4455/registration
          after:
            password:
              hooks:
                - hook: session
            default_browser_return_url: http://localhost:4455/
    
    # Identity schemas configuration
    identity:
      default_schema_id: default
      schemas:
        - id: default
          url: file:///etc/config/identity.default.schema.json
    
    # Hashers configuration
    hashers:
      algorithm: bcrypt
      bcrypt:
        cost: 8
    
    # Secrets for cookie and session management
    secrets:
      cookie:
        - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
      cipher:
        - 32-LONG-SECRET-NOT-SECURE-AT-ALL!!
    
    # Session configuration
    session:
      lifespan: 24h
      cookie:
        domain: localhost
        name: ory_kratos_session
        same_site: Lax
  
  # Default identity schema
  "identity.default.schema.json": |
    {
      "$id": "https://schemas.ory.sh/presets/kratos/quickstart/email-password/identity.schema.json",
      "$schema": "http://json-schema.org/draft-07/schema#",
      "title": "Person",
      "type": "object",
      "properties": {
        "traits": {
          "type": "object",
          "properties": {
            "email": {
              "type": "string",
              "format": "email",
              "title": "E-Mail",
              "minLength": 3,
              "ory.sh/kratos": {
                "credentials": {
                  "password": {
                    "identifier": true
                  },
                  "totp": {
                    "account_name": true
                  },
                  "webauthn": {
                    "identifier": true
                  }
                },
                "verification": {
                  "via": "email"
                },
                "recovery": {
                  "via": "email"
                }
              }
            },
            "name": {
              "type": "object",
              "properties": {
                "first": {
                  "title": "First Name",
                  "type": "string"
                },
                "last": {
                  "title": "Last Name",
                  "type": "string"
                }
              }
            }
          },
          "required": [
            "email"
          ],
          "additionalProperties": false
        }
      }
    }
