apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./rendered/zitadel/templates/configmap.yaml
  - ./rendered/zitadel/templates/deployment.yaml
  - ./rendered/zitadel/templates/initjob.yaml
  - ./rendered/zitadel/templates/secret_zitadel-masterkey.yaml
  - ./rendered/zitadel/templates/service.yaml
  - ./rendered/zitadel/templates/serviceaccount.yaml
  - ./rendered/zitadel/templates/setupjob.yaml

  - ./rendered/postgresql/templates/secrets.yaml
  - ./rendered/postgresql/templates/serviceaccount.yaml
  - ./rendered/postgresql/templates/primary/configmap.yaml
  - ./rendered/postgresql/templates/primary/networkpolicy.yaml
  - ./rendered/postgresql/templates/primary/pdb.yaml
  - ./rendered/postgresql/templates/primary/statefulset.yaml
  - ./rendered/postgresql/templates/primary/svc-headless.yaml
  - ./rendered/postgresql/templates/primary/svc.yaml
