---
# Source: cockroachdb/templates/cronjob-ca-certSelfSigner.yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cockroachdb-rotate-self-signer
  namespace: "default"
  labels:
    helm.sh/chart: cockroachdb-17.0.1
    app.kubernetes.io/name: cockroachdb
    app.kubernetes.io/instance: "cockroachdb"
    app.kubernetes.io/managed-by: "Helm"
spec:
  schedule: 0 0 1 */11 *
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        metadata:
        spec:
          restartPolicy: Never
          containers:
          - name: cert-rotate-job
            image: "gcr.io/cockroachlabs-helm-charts/cockroach-self-signer-cert:1.8"
            imagePullPolicy: "IfNotPresent"
            args:
            - rotate
            - --ca
            - --ca-duration=43800h
            - --ca-expiry=648h
            - --ca-cron=0 0 1 */11 *
            - --readiness-wait=30s
            - --pod-update-timeout=2m
            env:
            - name: STATEFULSET_NAME
              value: cockroachdb
            - name: NAMESPACE
              value: default
            - name: CLUSTER_DOMAIN
              value: cluster.local
          serviceAccountName: cockroachdb-rotate-self-signer
