---
# Source: cockroachdb/templates/job-certSelfSigner.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: cockroachdb-self-signer
  namespace: "default"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "4"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
  labels:
    helm.sh/chart: cockroachdb-17.0.1
    app.kubernetes.io/name: cockroachdb
    app.kubernetes.io/instance: "cockroachdb"
    app.kubernetes.io/managed-by: "Helm"
spec:
  template:
    metadata:
      name: cockroachdb-self-signer
      labels:
        helm.sh/chart: cockroachdb-17.0.1
        app.kubernetes.io/name: cockroachdb
        app.kubernetes.io/instance: "cockroachdb"
        app.kubernetes.io/managed-by: "Helm"
    spec:
      securityContext:
        seccompProfile:
          type: "RuntimeDefault"
        runAsGroup: 1000
        runAsUser: 1000
        fsGroup: 1000
        runAsNonRoot: true
      restartPolicy: Never
      containers:
        - name: cert-generate-job
          image: "gcr.io/cockroachlabs-helm-charts/cockroach-self-signer-cert:1.8"
          imagePullPolicy: "IfNotPresent"
          args:
            - generate
            - --ca-duration=43800h
            - --ca-expiry=648h
            - --client-duration=672h
            - --client-expiry=48h
            - --node-duration=8760h
            - --node-expiry=168h
          env:
          - name: STATEFULSET_NAME
            value: cockroachdb
          - name: NAMESPACE
            value: "default"
          - name: CLUSTER_DOMAIN
            value: cluster.local
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
      serviceAccountName: cockroachdb-self-signer
