---
# Source: cockroachdb/templates/rolebinding-certRotateSelfSigner.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cockroachdb-rotate-self-signer
  namespace: "default"
  labels:
    helm.sh/chart: cockroachdb-17.0.1
    app.kubernetes.io/name: cockroachdb
    app.kubernetes.io/instance: "cockroachdb"
    app.kubernetes.io/managed-by: "Helm"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cockroachdb-rotate-self-signer
subjects:
  - kind: ServiceAccount
    name: cockroachdb-rotate-self-signer
    namespace: "default"
