---
# Source: cockroachdb/templates/serviceaccount.yaml
kind: ServiceAccount
apiVersion: v1
metadata:
  name: cockroachdb
  namespace: "default"
  labels:
    helm.sh/chart: cockroachdb-17.0.1
    app.kubernetes.io/name: cockroachdb
    app.kubernetes.io/instance: "cockroachdb"
    app.kubernetes.io/managed-by: "Helm"
