---
# Source: kratos/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: kratos
  namespace: default
  labels:
    app.kubernetes.io/name: kratos
    helm.sh/chart: kratos-0.55.0
    app.kubernetes.io/instance: kratos
    app.kubernetes.io/version: "v1.3.1"
    app.kubernetes.io/managed-by: Helm
  annotations:
    helm.sh/hook: pre-install, pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "0"
    helm.sh/resource-policy: keep
type: Opaque
data:
  dsn: ""
  # Generate a random secret if the user doesn't give one. User given secret has priority
  secretsDefault: "dU13b1VQTkJESnFPa2VXVkMyQXl5QjFRaUVkaXdHSks="
  secretsCookie: "bU8wZUNJcXAzVEU3MnBoY0loOWJ0VW0yRDRtRDdrQ2w="
  secretsCipher: "UFdOSXN0YUlhZkl4anNDMEdSazBabWtMSnBzR0xaSlU="
