---
# Source: kratos/templates/service-admin.yaml
apiVersion: v1
kind: Service
metadata:
  name: kratos-admin
  namespace: default
  labels:
    app.kubernetes.io/component: admin
    app.kubernetes.io/name: kratos
    helm.sh/chart: kratos-0.55.0
    app.kubernetes.io/instance: kratos
    app.kubernetes.io/version: "v1.3.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http-admin
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: kratos
    app.kubernetes.io/instance: kratos
