---
# Source: kratos/templates/statefulset-mail.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kratos-courier
  namespace: default
  labels:
    app.kubernetes.io/component: courier
    app.kubernetes.io/name: kratos
    helm.sh/chart: kratos-0.55.0
    app.kubernetes.io/instance: kratos
    app.kubernetes.io/version: "v1.3.1"
    app.kubernetes.io/managed-by: Helm
  annotations:
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kratos-courier
      app.kubernetes.io/instance: kratos
  serviceName: kratos-courier
  replicas: 1
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kratos-courier
        app.kubernetes.io/instance: kratos
        app.kubernetes.io/component: courier
      annotations:        
        checksum/kratos-config: 4e82fa0677335948e37d84d390c101587bf9e67da8596ed0828c7375e36b3afb
        checksum/kratos-templates: 01ba4719c80b6fe911b091a7c05124b64eeece964e09c058ef8f9805daca546b
        checksum/kratos-secrets: 94fedb589e43afc8ced3fd77c3b1d1c95dd02191cfceadedf44bd59ab1984a3e
    spec:
      serviceAccountName: kratos
      terminationGracePeriodSeconds: 60
      containers:
        - name: kratos-courier
          image: oryd/kratos:v1.3.1
          imagePullPolicy: IfNotPresent
          args:
            - courier
            - watch 
            - --config
            - /etc/config/kratos.yaml
            - --expose-metrics-port
            - "4434"
          volumeMounts:
            - name: kratos-config-volume
              mountPath: /etc/config
              readOnly: true
          env:
            - name: LOG_FORMAT
              value: json
            - name: LOG_LEVEL
              value: trace
            - name: SECRETS_DEFAULT
              valueFrom:
                secretKeyRef:
                  name: kratos
                  key: secretsDefault
                  optional: true
            - name: SECRETS_COOKIE
              valueFrom:
                secretKeyRef:
                  name: kratos
                  key: secretsCookie
                  optional: true
            - name: SECRETS_CIPHER
              valueFrom:
                secretKeyRef:
                  name: kratos
                  key: secretsCipher
                  optional: true
          ports:
            - name: http-metrics
              containerPort: 4434
              protocol: TCP
          resources:
            null
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 65534
            runAsNonRoot: true
            runAsUser: 65534
            seLinuxOptions:
              level: s0:c123,c456
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: kratos-config-volume
          configMap:
            name: kratos-config
      securityContext:
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
        seccompProfile:
          type: RuntimeDefault
